name: Test
on: [push]

jobs:
  TEST:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo ${{ env.TEST.SEC }} > index.html
          mv index.html /tmp
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: |
          git checkout gh-pages
          mv /tmp/index.html .
          git add --all
          git commit -m "add to gh-pages"
          git push